/** Market Control: curated catalogue plus a read-only preview of the two live
 * server-generated rotations. The preview shares the same endpoint and helper
 * as players, so its cadence can never drift from the actual storefront. */
(function () {
  'use strict';
  var entries = [], gear = [], characters = [], levels = [], rotations = {}, filter = 'all', current = null;
  var list = document.getElementById('market-entry-list'), count = document.getElementById('market-admin-count'), summary = document.getElementById('market-rotation-summary'), modal = document.getElementById('market-entry-modal');
  var type = document.getElementById('market-entry-type'), definition = document.getElementById('market-entry-definition'), rank = document.getElementById('market-entry-rank');

  function can(key) { return typeof window.pwHasPermission === 'function' && window.pwHasPermission(key); }
  function esc(value) { var node = document.createElement('div'); node.textContent = value == null ? '' : String(value); return node.innerHTML; }
  /* Market Control is often opened straight after creating equipment in Mission
   * Control. Catalogue reads must therefore bypass any browser or proxy copy of
   * the old response, otherwise a newly saved helmet looks like it does not
   * exist until a hard refresh. */
  function request(url, payload) { var options = { credentials: 'same-origin', cache: 'no-store' }; if (payload) { payload.csrf = window.PW_AUTH && window.PW_AUTH.csrf ? window.PW_AUTH.csrf : ''; options.method = 'POST'; options.headers = { 'Content-Type': 'application/json' }; options.body = JSON.stringify(payload); } return fetch(url, options).then(function (response) { return response.json().catch(function () { return {}; }); }).then(function (data) { if (!data.ok) throw new Error(data.error || 'The market request could not be completed.'); return data; }); }
  function catalogue() { return type.value === 'gear' ? gear : characters; }
  function definitionLabel(item) { return item.name + (type.value === 'gear' ? ' · ' + (item.tier || 'common') + ' ' + String(item.slot || '').replace(/-/g, ' ') : ' · ' + (item.role || 'crew')) + (item.is_enabled ? '' : ' (disabled source)'); }
  function fillDefinitions(selected) { definition.innerHTML = ''; catalogue().forEach(function (item) { var option = document.createElement('option'); option.value = item.id; option.textContent = definitionLabel(item); option.disabled = !item.is_enabled && Number(item.id) !== Number(selected); option.selected = Number(item.id) === Number(selected); definition.appendChild(option); }); if (!definition.options.length) definition.innerHTML = '<option value="">No compatible catalogue entries</option>'; }
  function fillRanks(selected) { rank.innerHTML = ''; levels.forEach(function (level) { var option = document.createElement('option'); option.value = level.number; option.textContent = 'Rank ' + level.number + ' · ' + level.name + ' (' + Number(level.threshold).toLocaleString() + ' rep)'; option.selected = Number(level.number) === Number(selected); rank.appendChild(option); }); if (!rank.options.length) rank.innerHTML = '<option value="1">Rank 1</option>'; }
  function setError(message) { document.getElementById('market-entry-modal-error').textContent = message || ''; }
  function displayCount() { var visible = entries.filter(function (entry) { return filter === 'all' || entry.offer_type === filter; }); count.textContent = visible.length + (visible.length === 1 ? ' market offer' : ' market offers'); }
  function renderRotations() { if (!summary) return; summary.innerHTML = ['gear', 'character'].map(function (kind) { var rotation = rotations[kind] || {}, items = rotation.items || [], label = kind === 'gear' ? 'Equipment rotation' : 'Character rotation', when = kind === 'gear' ? '00:00 / 06:00 / 12:00 / 18:00 UTC' : '01:00 / 07:00 / 13:00 / 19:00 UTC'; return '<article class="market-rotation-card ' + (kind === 'character' ? 'is-character' : '') + '"><div class="market-rotation-card-head"><span class="eyebrow">' + when + '</span><strong>' + label + '</strong></div><small>Current window ends ' + esc(rotation.ends_at || 'after the next sync') + ' UTC</small><ul>' + (items.length ? items.map(function (item) { return '<li><span>' + esc(item.name || 'Retired entry') + '</span><b>' + Number(item.stock_remaining) + '/' + Number(item.stock_initial) + ' · ' + Number(item.credit_price).toLocaleString() + ' cr</b></li>'; }).join('') : '<li class="market-rotation-empty">No active catalogue entries were selected.</li>') + '</ul></article>'; }).join(''); }
  function renderEntries() { if (!list) return; var visible = entries.filter(function (entry) { return filter === 'all' || entry.offer_type === filter; }); displayCount(); if (!visible.length) { list.innerHTML = '<div class="admin-list-empty">No matching market offers yet. Add a gear or character catalogue entry to let it enter future rotations.</div>'; return; } list.innerHTML = ''; visible.forEach(function (entry) { var row = document.createElement('button'); row.type = 'button'; row.className = 'admin-row market-admin-row'; row.disabled = !can('market.manage'); var sourceDetail = entry.offer_type === 'gear' ? ((entry.tier || 'common') + ' · ' + String(entry.slot || '').replace(/-/g, ' ')) : (entry.role || 'crew recruit'); row.innerHTML = '<span class="market-admin-item"><strong>' + esc(entry.name || 'Retired source') + '</strong><small>' + esc(sourceDetail) + '</small></span><span class="market-admin-type ' + (entry.offer_type === 'character' ? 'is-character' : '') + '">' + esc(entry.offer_type === 'gear' ? 'Equipment' : 'Character') + '</span><span class="market-admin-value"><b>' + Number(entry.credit_price).toLocaleString() + '</b> credits</span><span class="market-admin-value">Rank <b>' + Number(entry.required_reputation_level) + '</b></span><span class="market-admin-value">Weight <b>' + Number(entry.rotation_weight) + '</b><br>Stock <b>' + Number(entry.stock_per_rotation) + '</b></span><span class="market-admin-status"><span class="report-status ' + (entry.is_enabled ? 'report-status-resolved' : 'report-status-pending') + '">' + (entry.is_enabled ? 'Enabled' : 'Disabled') + '</span>' + (!entry.source_enabled ? '<small>Source disabled</small>' : '') + '</span>'; row.addEventListener('click', function () { if (can('market.manage')) open(entry); }); list.appendChild(row); }); }
  function switchFilter(value) { filter = value; document.querySelectorAll('[data-market-filter]').forEach(function (tab) { var active = tab.getAttribute('data-market-filter') === value; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', active ? 'true' : 'false'); }); renderEntries(); }
  function open(entry) { current = entry || null; document.getElementById('market-entry-modal-title').textContent = current ? 'Edit Market Offer' : 'Add Market Offer'; document.getElementById('market-entry-modal-sub').textContent = current ? 'The product is immutable once configured, so historical and live rotations keep their identity. Change price, rank gate, weight, stock, or availability here.' : 'Choose an existing equipment item or character. It joins future shared rotations according to its weight.'; type.value = current ? current.offer_type : (filter === 'character' ? 'character' : 'gear'); fillDefinitions(current ? (current.offer_type === 'gear' ? current.loot_definition_id : current.crew_definition_id) : null); fillRanks(current ? current.required_reputation_level : 1); document.getElementById('market-entry-price').value = current ? current.credit_price : 250; document.getElementById('market-entry-weight').value = current ? current.rotation_weight : 100; document.getElementById('market-entry-stock').value = current ? current.stock_per_rotation : 1; document.getElementById('market-entry-enabled').checked = current ? current.is_enabled : true; type.disabled = !!current; definition.disabled = !!current; document.getElementById('market-entry-save-btn').disabled = !can('market.manage') || !definition.value; setError(''); modal.hidden = false; setTimeout(function () { current ? document.getElementById('market-entry-price').focus() : definition.focus(); }, 20); }
  function close() { modal.hidden = true; current = null; }
  function save() { if (!can('market.manage')) return; var button = document.getElementById('market-entry-save-btn'); var payload = { offer_type: type.value, definition_id: definition.value, credit_price: document.getElementById('market-entry-price').value, required_reputation_level: rank.value, rotation_weight: document.getElementById('market-entry-weight').value, stock_per_rotation: document.getElementById('market-entry-stock').value, is_enabled: document.getElementById('market-entry-enabled').checked }; if (current) payload.id = current.id; button.disabled = true; button.classList.add('is-busy'); setError(''); request('/api/admin/market/save.php', payload).then(function () { close(); return load(); }).catch(function (error) { setError(error.message); }).then(function () { button.disabled = !can('market.manage'); button.classList.remove('is-busy'); }); }
  function load() { return request('/api/admin/market/list.php?refresh=' + Date.now()).then(function (data) { entries = data.entries || []; gear = data.gear || []; characters = data.characters || []; levels = data.reputation_levels || []; rotations = data.rotations || {}; renderRotations(); renderEntries(); }).catch(function (error) { list.innerHTML = '<div class="admin-list-empty">' + esc(error.message || 'Could not load Market Control.') + '</div>'; summary.innerHTML = ''; }); }
  document.querySelectorAll('[data-market-filter]').forEach(function (tab) { tab.addEventListener('click', function () { switchFilter(tab.getAttribute('data-market-filter')); }); }); document.getElementById('market-entry-create-btn').addEventListener('click', function () { open(null); }); type.addEventListener('change', function () { fillDefinitions(null); document.getElementById('market-entry-save-btn').disabled = !can('market.manage') || !definition.value; }); document.getElementById('market-entry-modal-close').addEventListener('click', close); document.getElementById('market-entry-cancel-btn').addEventListener('click', close); modal.querySelector('.admin-modal-backdrop').addEventListener('click', close); document.getElementById('market-entry-save-btn').addEventListener('click', save);
  window.loadMarketControl = function () { switchFilter(filter); return load(); };
}());
