-- Welcome email visual refresh
-- Run once in phpMyAdmin after deploying. It updates only the original
-- uncustomised Welcome template, so administrator-edited copy is preserved.

UPDATE mail_templates
SET
  html_body = '<div style="margin:0;padding:36px 16px;background-color:#0b0815;color:#eee8ff;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:620px;background-color:#171027;border:1px solid #4c3477;border-radius:14px;overflow:hidden;"><tr><td style="padding:18px 34px;background:linear-gradient(115deg,#2d1b54,#171027);border-bottom:1px solid #62478f;"><span style="display:inline-block;margin-right:10px;color:#f2c96d;font-family:Georgia,serif;font-size:18px;font-weight:bold;letter-spacing:1px;">TPW</span><span style="color:#d9c7ff;font-size:11px;font-weight:bold;letter-spacing:2px;text-transform:uppercase;">A new chronicle begins</span></td></tr><tr><td style="padding:38px 34px 30px;"><p style="margin:0 0 10px;color:#f2c96d;font-size:11px;font-weight:bold;letter-spacing:2px;text-transform:uppercase;">Welcome to the Pantheon</p><h1 style="margin:0 0 18px;color:#fff7e4;font-family:Georgia,Times New Roman,serif;font-size:31px;font-weight:normal;line-height:1.2;">Welcome, {{recipient_name}}.</h1><p style="margin:0 0 16px;color:#d8cceb;font-size:16px;line-height:1.7;">Your account is ready. The worlds, books, and community of {{site_name}} are now open for you to explore at your own pace.</p><p style="margin:0 0 28px;color:#a99abd;font-size:14px;line-height:1.6;">Begin with a story, follow a thread through the lore, or step into the conversations already unfolding in Nexus Veil.</p><table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td style="border-radius:6px;background-color:#7044c7;"><a href="{{login_url}}" style="display:inline-block;padding:13px 20px;color:#fff;text-decoration:none;font-size:12px;font-weight:bold;letter-spacing:1.2px;text-transform:uppercase;">Enter {{site_name}} &rarr;</a></td></tr></table></td></tr><tr><td style="padding:18px 34px;border-top:1px solid #3d2b60;color:#9687ae;font-size:11px;line-height:1.5;">This transmission was sent because a new account was created for {{recipient_email}}. Keep this message for your records.</td></tr></table></td></tr></table></div>',
  text_body = 'Welcome, {{recipient_name}}.\n\nYour account is ready. The worlds, books, and community of {{site_name}} are now open for you to explore at your own pace.\n\nEnter {{site_name}}: {{login_url}}\n\nThis message was sent because a new account was created for {{recipient_email}}.'
WHERE template_key = 'welcome'
  AND html_body = '<p>Welcome, {{recipient_name}}.</p><p>Your account is ready. You can sign in and begin exploring the worlds, books, and community whenever you are ready.</p><p><a href="{{login_url}}">Enter {{site_name}}</a></p>';
